name: OctoDNS Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
      
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: octodns-sync
      uses: solvaholic/octodns-sync@v3.0.1
      with:
        config_path: ./config/production.yaml
        doit: '--doit' 
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
